### ISSUE TITLE
Bundle secret source not found

### ISSUE THREAD

**Issue by GeroL** [cert-manager/trust-manager#120]
HI, I might be missing something here:

I setup issuers and certificates for linkerd and I try to get the Root CA into the config map as required.
The error I get is: Bundle source was not found: failed to retrieve bundle from source: Secret "linkerd-identity-issuer" not found

```
--- # Linkerd CA 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h0m0s
  renewBefore: 25h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
spec:
  sources:
  - secret:
      name: linkerd-identity-issuer
      key: ca.crt
  target:
    configMap:
      key: ca-bundle.crt
```

When I use the console and check the secret I can that the data itself is there.
Do you have a hint on what I am missing here?
```
main@server5:~$ microk8s kubectl describe secret linkerd-identity-issuer -n linkerd
Name:         linkerd-identity-issuer
Namespace:    linkerd
Labels:       controller.cert-manager.io/fao=true
Annotations:  cert-manager.io/alt-names: identity.linkerd.cluster.local
              cert-manager.io/certificate-name: linkerd-identity-issuer
              cert-manager.io/common-name: identity.linkerd.cluster.local
              cert-manager.io/ip-sans:
              cert-manager.io/issuer-group:
              cert-manager.io/issuer-kind: Issuer
              cert-manager.io/issuer-name: linkerd-trust-anchor
              cert-manager.io/uri-sans:

Type:  kubernetes.io/tls

Data
====
tls.crt:  749 bytes
tls.key:  227 bytes
ca.crt:   595 bytes
```
