### ISSUE TITLE
Feature: per namespace trust bundle

### ISSUE THREAD

**Issue by KLuuKer** [cert-manager/trust-manager#131]
I have multiple namespaces that don't trust each other and have their own per namespace root ca

I would like to be able to specify a bundle per namespace instead of 1 for the whole cluster 

This would also help with the cleanup when said namespaces get deleted

**Comment by erikgb** [comment]
This should already be possible using the field `spec.target.namesspaceSelector`: https://cert-manager.io/docs/projects/trust-manager/api-reference/#bundlespectargetnamespaceselector. To target a single namespace, you can achieve that:

```yaml
spec:
  target:
    namespaceSelector:
      kubernetes.io/metadata.name: my-namespace
```
