### ISSUE TITLE
BUG:  unsuppotted `useDefaultCAs: false`

### ISSUE THREAD

**Issue by pavel-jancik** [cert-manager/trust-manager#133]
If  trying to set `source.useDefaultCAs` to `false` the admission webhook prevents creation of the bundle.

How to reproduce:
```sh
cat  <<EOF | kubectl apply -f -
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: my-org.com-ca
spec:
  sources:
  - useDefaultCAs: false

  #- secret:
  #    name: my-org.com-ca
  #    key: "tls.crt"

  target:
    configMap:
      key: "certs.pem"
    namespaceSelector:
      matchLabels: {}
EOF
```

Error output:
`admission webhook "trust.cert-manager.io" denied the request: spec.sources.[0]: Forbidden: must define exactly one source type for each item but found 0 defined types`

Workaround is trivial comment the `useDefaultCAs` entry, but still one would expect the `false` is supported value.

**Comment by inteon** [comment]
@pavel-jancik could you explain what `useDefaultCAs: false` would mean?
Currently, the default value is `false`, but each item in the sources array needs to contain exactly one source.
For that reason, specifying `useDefaultCAs: false` does not make sense.

**Comment by pavel-jancik** [comment]
I just wanted to explicitly mention it. I.e., make the default value visible in the bundle CR (for documentation purposes)
  so that it is obvious for others that in the resulting config maps no other trusted CA will be included.
 
Note that, I have been cleaning the example above; the idea was not to create an empty bundle.
I have been using:
```
spec:
  sources:
  # Do not inject a long list generally trusted CA
  - useDefaultCAs: false

  # A Secret in the trust-manager namespace
  - secret:
      name: "our-org-ca"
      key: "ca.crt"
```
