### ISSUE TITLE
Is there a way to specify the domain

### ISSUE THREAD

**Issue by vishrantgupta** [cert-manager/trust-manager#150]
I am looking for a way to create the Bundle with the domain in order to create the PEM

```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trust-bundle
  namespace: default
spec:
  sources:
  - domain: https://example.com           # <-- expecting the trust manager to pull the PEM by domain
  target:
    configMap:
      key: trust.pem
```
