### ISSUE TITLE
support extra annotations on resoures in helm chart

### ISSUE THREAD

**Issue by thesuperzapper** [cert-manager/trust-manager#175]
I would like to be able to set "global" annotations for all resources in the trust-manager helm chart.

The main purpose of this is to allow a single "combined" chart of `cert-manager` and `trust-manager` to be applied successfully using Argo CD. Right now, if a combined chart is created, the first sync will always fail (because `trust-manager` depends on `cert-manager` being ready). 

However, if I could set annotations on all resources, I would be able to make use of [Argo CD's Sync Waves](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-do-i-configure-waves) to put all the `trust-manager` resources in a wave that happens after `cert-manager`. 

For example, we might add a value called `app.annotations` to the chart (which adds no annotations by default), and use it like follows:

```yaml
app:
  annotations:
    ## assuming cert-manager has a lower wave (or no wave) set
    argocd.argoproj.io/sync-wave: "5"
```
