### ISSUE TITLE
More flexible and better organized target specification in API

### ISSUE THREAD

**Issue by erikgb** [cert-manager/trust-manager#243]
I will start with a "max" target specification using the existing API (also including #235 - which I think will be merged before this issue is eventually addressed):

````yaml
target:
    configMap:
      key: root-certs.pem
    secret:
      key: root-certs.pem
    additionalFormats:
      jks:
        key: bundle.jks
        password: jks-password
      pkcs12:
        key: bundle.p12
        password: pkcs12-password
````

I can identify several issues with this specification structure:

- It forces me to include a PEM encoded in target configmap/secret. There is no way to opt-out and just use JKS/PKCS12.
- The term `additional` appears a bit "discriminating", and does not motivate users to suggest (or contribute) new formats (e.g. DER).
- The PEM encoded bundle allows different `key` in configmap and secret, while for "additional formats" this is not supported.
- Encodings that require a password do not support specifying a different password for configmap and secret.
- The format does not allow me to output the same encoding in two different keys of target. I am not sure if we should support this, but it could theoretically make sense in a migration scenario. But the simple workaround is just to create a new bundle for migration.

To solve most of these issues, I suggest a more flexible (and less "discriminating") structure. It might appear more complex, but remember that most users will probably not use a "max" specification, and only specify relevant fields for their setup.

````yaml
target:
    configMap:
      pem:
        key: root-certs.pem
      jks:
        key: bundle.jks
        password: jks-password
      pkcs12:
        key: bundle.p12
        password: pkcs12-password
    secret:
      pem:
        key: root-certs.pem
      jks:
        key: bundle.jks
        password: jks-password
      pkcs12:
        key: bundle.p12
        password: pkcs12-password
````

**Comment by hazmat345** [comment]
Maybe this could also be a chance to bring the target side more in line with the sources side? What would you think about something more like this instead:

```
targets:
  - configMap:
      format: pem
      key: root-certs.pem
  - configMap:
      format: jks
      key: bundle.jks
      password: jks-password
  - configMap:
      format: pkcs12
      key: bundle.p12
      password: pkcs12-password
  - secret:
      format: pem
      key: root-certs.pem
  - secret:
      format: jks
      key: bundle.jks
      password: jks-password
  - secret:
      format: pkcs12
      key: bundle.p12
      password: pkcs12-password
```

**Comment by erikgb** [comment]
@hazmat345 Thanks for your input. I like your suggestion. It's probably better than what I suggested initially in this issue! 😄 We use kustomize a lot, and patching arrays could be troublesome. What if we separated config from secret, but used your suggestion with a `format` field? That would allow us to use `key` as mapKey when giving the arrays map semantics.

I agree that `sources` and `target` should be aligned in the API, but we could also adjust the `sources` part when breaking the API.

**Comment by erikgb** [comment]
Inspired by the suggestion from @hazmat345, I think the following might work well:

````yaml
target:
  configMap:
    - format: pem
      key: root-certs.pem
    - format: jks
      key: bundle.jks
      password: jks-password
    - format: pkcs12
      key: bundle.p12
      password: pkcs12-password
  secret:
    - format: pem
      key: root-certs.pem
    - format: jks
      key: bundle.jks
      password: jks-password
    - format: pkcs12
      key: bundle.p12
      password: pkcs12-password
````

That will allow us to set map semantics on the arrays in `configMap` and `secret` fields, with `key` as the map key. With this structure, the Bundle OpenAPI spec will validate the fact that `key` must be unique in a single target (configMap or secret).

**Comment by erikgb** [comment]
I agree that we should not support multiple configmaps/secrets. The increased controller complexity is just not worth it. Users that want/need this, can simply create additional bundle resources using the same sources.

But when it comes to specifying the target resource content, I don't think we should have a "magic" default target key for PEM bundles. I think this will bite us at some point in the future. 😁 I agree that PEM is probably the most common format, so it should be easy to configure it. Wouldn't the following be easy enough to represent your example above?

````yaml
target:
  configMap:
    - format: jks
      key: bundle.jks
      password: whatever
  secret:
    # PEM is the default format
    - key: bundle.pem
````
