### ISSUE TITLE
Evaluate trust namespace value as template

### ISSUE THREAD

**Issue by heruan** [cert-manager/trust-manager#291]
When installing trust-manager as a subchart (i.e. dependency) it would be useful to automatically set the trust namespace value to the release namespace, or another dynamic value. At the moment this is unfortunately not possibile since the `app.trust.namespace` value is evaluated as-is and so it needs to be always explicitly specified if you don't want the default one.

This can be easily solved if the value were [evaluated as a template](https://itnext.io/reference-other-values-in-helm-chart-values-file-19d44d9276c7), e.g.

```diff
 metadata:
   name: {{ include "trust-manager.name" . }}
-  namespace: {{ .Values.app.trust.namespace }}
+  namespace: {{ tpl .Values.app.trust.namespace . }}
```

Then it would be possibile to set the trust namespace dynamically, e.g.

```yaml
# Subchart configuration when trust-manager is a dependency
trust-manager:
  app:
    trust:
      namespace: {{ .Release.Namespace }}
```

Is this something that might be worth a PR? I'd be happy to contribute!
