### ISSUE TITLE
Bundle generating empty truststore.p12 when no password is provided

### ISSUE THREAD

**Issue by arjunprasad2143** [cert-manager/trust-manager#296]
I used the below config to create a pkcs12 additional format bundle without password. But the created truststore is empty. 

```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: truststore
spec:
  sources:
    - secret:
        key: root-certs.pem
        name: trusted-certs
  target:
    additionalFormats:
      pkcs12:
        key: truststore.p12
        password: ''
    secret:
      key: root-certs.pem
```

The secret contains the required bundle, but the truststore.p12 is empty.
The result remains the same when I use a configmap source.
