### ISSUE TITLE
Empty Target field in kubectl get bundle

### ISSUE THREAD

**Issue by qds-x** [cert-manager/trust-manager#343]
After having upgraded to 0.9.2 from 0.5.0 we see the 'Target' field empty in the following output
```
➜  k get bundle
NAME                   TARGET   SYNCED   REASON   AGE
test-bundle-injected            True     Synced   4m27s
```
Everything functions as expected.

Tested this on a fresh minikube instance and got the same thing. I used a very simple bundle defn:
```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: "test-bundle-injected" 
spec:
  sources:
  - inLine: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  target:
    configMap:
      key: cert.pem
```
Happy to provide more information if required.
