### ISSUE TITLE
[chart] Allow creation of serviceMonitor in a different namespace

### ISSUE THREAD

**Issue by jsalatiel** [cert-manager/trust-manager#452]
Currently cert-manager chart allows to have 
```
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      namespace: monitoring
```

But serviceMonitor in trust-manager does not accept the namespace key. So
```
  app:
    metrics:
      service:
        servicemonitor:
          enabled: true
```
will always create the serviceMonitor inside the trust-manager monitor.
Please add a parameter to accept creation in another namespace.
