### ISSUE TITLE
Error in helm chart. Namespace in role and rolebinding is wrong

### ISSUE THREAD

**Issue by oleksiyp** [cert-manager/trust-manager#454]
```
# Source: trust-manager/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: trust-manager
    helm.sh/chart: trust-manager-v0.12.0
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trust-manager
subjects:
- kind: ServiceAccount
  name: trust-manager
  namespace: infra
```

![image](https://github.com/user-attachments/assets/fdb066b4-d448-4ec5-9a32-aacdc81b6c3c)
