### ISSUE TITLE
PKCS12 certificates cannot be used in FIPS environments

### ISSUE THREAD

**Issue by jstaf** [cert-manager/trust-manager#457]
trust-manager's .p12 certificates cannot be loaded on systems that enforce FIPS. Example CA bundle:

```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
spec:
  sources:
  - useDefaultCAs: true
  target:
    additionalFormats:
      pkcs12:
        key: ca-bundle.p12
        password: ""
    namespaceSelector:
      matchLabels:
        trust-manager/ca-bundle: enabled
    secret:
      key: ca-bundle.pem
```

And on a FIPS-enabled system, Java cannot load the ca-bundle.p12 certificate:

```
java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.security.NoSuchAlgorithmException: Cannot find any provider supporting PBEWithSHA1AndRC2_40
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
```

trust-manager should have an option to change the PKCS12 algorithm (not sure if I'm using the right words here to describe things) to a certificate format compatible with FIPS.
