### ISSUE TITLE
Add a top level variable called `enabled` to the Helm chart schema

### ISSUE THREAD

**Issue by AntonioND** [cert-manager/trust-manager#574]
cert-manager already does this, and it's quite useful when you're using it as a subchart because you don't need to create another variable in your own `values.yaml`. trust-manager has defined in its schema that it doesn't accept variables not defined in the schema, so it needs to be added in the original Helm chart.

https://github.com/cert-manager/cert-manager/blob/9aa47a01ded1a47e772909f03a816f1a73680769/deploy/charts/cert-manager/values.yaml#L1458-L1465

**Comment by erikgb** [comment]
This makes sense!

/good-first-issue
/help

**Comment by dhvll** [comment]
Hey I would like to work on this issue. Can you assign me ?

**Comment by hawksight** [comment]
This should be fixed in the next release. I tested wrapping with this Chart.yaml

```yaml
apiVersion: v2
# note os for open source. No closed source things here.
name: cert-manager-os-wrap
description: Install core open source cert-manager components together
type: application
version: 0.1.0
# Based on the core cert-manager version
appVersion: "1.14.4"
# Potentially many deps
dependencies:
- name: cert-manager
  version: "v1.16.3"
  repository: "https://charts.jetstack.io"
- name: cert-manager-approver-policy
  version: "v0.18.0"
  repository: "https://charts.jetstack.io"
- name: cert-manager-csi-driver
  version: "v0.10.1"
  repository: "https://charts.jetstack.io"
- name: trust-manager
  version: "v0.0.0"
  repository: "file:///Users/peter.fiddes/ghq/github.com/cert-manager/trust-manager/deploy/charts/trust-manager"
  condition: trust-manager.enabled
```

Note you would use the new version and proper repo such as:

```yaml
- name: trust-manager
  version: "v0.19.0"
  repository: "https://charts.jetstack.io"
  condition: trust-manager.enabled
```

I had to use the condition, mainly for CRD presence and because cert-manager is needed before trust-manager. You may need extra work for a one shot installation with a helm wrapper chart.
