### ISSUE TITLE
The crds is not installed automatically when trust-manager is a sub-chart

### ISSUE THREAD

**Issue by smallc2009** [cert-manager/trust-manager#629]
I'm using trust-manager as a dependency in my helm chart. when installing my helm chart, the crds for trust-manager failed to install automatically. 

**Error**
```
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "public-ca-with-internal-bundles" namespace: "" from "": no matches for kind "Bundle" in version "trust.cert-manager.io/v1alpha1"
ensure CRDs are installed first
```

Here is my Chart.yaml and Values.yaml. we publish a custom helm chart and deploy them with Octopus. 
**Chart.yaml**
```
apiVersion: v2
name: trust-manager
description: Trust manager for managing certificates
type: application

version: 0.0.0
appVersion: "0.0.0"

dependencies:
  - name: trust-manager
    version: "0.17.1"
    repository: https://charts.jetstack.io

```

**values.yaml**
```
trust-manager:
  crds:
    enabled: true
  app:
    webhook:
      tls:
        helmCert:
          enabled: true
  defaultPackageImage:
    repository: quay.io/jetstack/trust-pkg-debian-bookworm
    tag: "20230311.0"
```

Expection:

Support crd to install automatically during trust-manager is subchart.
