### ISSUE TITLE
High cpu and ram load on apiserver

### ISSUE THREAD

**Issue by EricPE69** [cert-manager/trust-manager#632]
On the fist start of trust-manager (v 0.16) it has to synchronize all the namespaces (about 200 to 300) with 2 secrets (2 bundles). 

Immediately after its launch we see a very strong increase in cpu and memory load of the apiserver. Sometimes the apiserver goes to "outofmemory".

When the bundles are synced the load decreases.

I attach the consumption graphs of the apiserver

![Image](https://github.com/user-attachments/assets/adcf4b2e-1b61-465b-9975-2812b0042c60)

**Comment by EricPE69** [comment]
Trust-manager is not the root of the problem: it’s a bad implementation of the "list" mode in the kube-apiserver.
See: https://kubernetes.io/blog/2024/12/17/kube-apiserver-api-streaming/

We encounter this problem because we have many secrets and many components  that make "list" queries on secrets.
In kubernetes 1.33 there is a new implementation of the "list" mode that fixes this anomaly.

But since we are still in version 1.29, we had to implement a workaround: we use the "flow control" API to limit the number of simultaneous executions (of list queries). See https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

FYI here are the flow-control objects we used:

```yaml
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: list-requests
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: list-requests
  rules:
    - resourceRules:
        - apiGroups: ['*']
          namespaces: ['*']
          resources: ['*']
          verbs: ['list']
          clusterScope: true
      subjects:
      - group:
          name: system:unauthenticated
        kind: Group
      - group:
          name: system:authenticated
        kind: Group
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: list-requests
spec:
  type: Limited
  limited:
    nominalConcurrencyShares: 1
    borrowingLimitPercent: 0
    limitResponse:
      type: Queue
      queuing: {}

```
